server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.1.222:33078/golf
    username: golf
    password: golf_123#
  jpa:
    show-sql: true
  application:
    name: wood-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true    # 显示真实的ip地址，默认是false
