server:
  port: 8082
student:
  servicePath: http://localhost:8081/provider/findStudent/
spring:
  application:
    name: wood-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

